/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import settings.ProjectSettings;

/**
 *
 * @author Gabriel
 */
public class SimulationSettingsFrame extends javax.swing.JFrame {

	private static final long serialVersionUID = 1L;
	
	/**
     * Creates new form SimulationSettingsFrame
     */
    public SimulationSettingsFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSimulationSettings = new javax.swing.JPanel();
        jLabelSimulationSettings = new javax.swing.JLabel();
        jLabelSimulationSpeed = new javax.swing.JLabel();
        jSpinnerSimulationSpeed = new javax.swing.JSpinner();
        jButtonOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelSimulationSettings.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabelSimulationSettings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSimulationSettings.setText("Simulation settings:");

        jLabelSimulationSpeed.setText("Simulation speed (miliseconds):");

        jSpinnerSimulationSpeed.setValue(20);

        jButtonOk.setText("Ok");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSimulationSettingsLayout = new javax.swing.GroupLayout(jPanelSimulationSettings);
        jPanelSimulationSettings.setLayout(jPanelSimulationSettingsLayout);
        jPanelSimulationSettingsLayout.setHorizontalGroup(
            jPanelSimulationSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSimulationSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSimulationSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSimulationSettings, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                    .addGroup(jPanelSimulationSettingsLayout.createSequentialGroup()
                        .addComponent(jLabelSimulationSpeed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerSimulationSpeed))
                    .addComponent(jButtonOk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelSimulationSettingsLayout.setVerticalGroup(
            jPanelSimulationSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSimulationSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSimulationSettings)
                .addGap(18, 18, 18)
                .addGroup(jPanelSimulationSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSimulationSpeed)
                    .addComponent(jSpinnerSimulationSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonOk)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSimulationSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSimulationSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        ProjectSettings.setSimulationSpeed((int)this.jSpinnerSimulationSpeed.getValue());
        this.dispose();
    }//GEN-LAST:event_jButtonOkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOk;
    private javax.swing.JLabel jLabelSimulationSettings;
    private javax.swing.JLabel jLabelSimulationSpeed;
    private javax.swing.JPanel jPanelSimulationSettings;
    private javax.swing.JSpinner jSpinnerSimulationSpeed;
    // End of variables declaration//GEN-END:variables
}
